# Generated by Django 4.0.3 on 2022-03-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('author_img', models.ImageField(upload_to='author_img')),
            ],
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_name', models.CharField(max_length=200)),
                ('cg_descriptions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('news_status', models.BooleanField(default=False)),
                ('comment_status', models.BooleanField(default=False)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newsapp.author')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.catagories')),
            ],
        ),
    ]
