# Generated by Django 4.0.3 on 2022-03-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_news_img_sub_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_new',
            name='sub_description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]
