# Generated by Django 4.0.3 on 2022-03-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_alter_news_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_new',
            name='img',
            field=models.ImageField(default='null', upload_to='Sub_img'),
            preserve_default=False,
        ),
    ]
