# Generated by Django 4.0.3 on 2022-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_sub_new_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='img',
            field=models.ImageField(default='null', upload_to='cat_img'),
            preserve_default=False,
        ),
    ]
